package com.narayanjoshi.gplapplication;

import javafx.fxml.FXML;
import javafx.scene.canvas.Canvas;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;

/**
 * The {@code GPLController} class is a controller to handle all type of
 * event generated by GPL application using UI.
 *
 * @author Narayan Joshi
 * @since v1.0
 * */
public class GPLController {

    /**
     * This canvasId is responsible for making all shapes and performing output on the display box.
     * @see Canvas for more information
     * */
    @FXML
    public Canvas canvasId;

    /**
     * This inputMultipleCodeText holds multiple line code for further processing.
     * @see TextArea for more information
     * */
    @FXML
    private TextArea inputMultipleCodeText;

    /**
     * This inputSingleCodeText holds single line code for further processing.
     * @see TextField for more information
     * */
    @FXML
    private TextField inputSingleCodeText;

    /**
     * The run button form GLP application is the entry point for processing as per the given instruction
     * */
    @FXML
    protected void onRunButtonClick() {

        String commandSingle = inputSingleCodeText.getText();
        String commandMultiple = inputMultipleCodeText.getText();

        CommandParser commandParser= new CommandParser(canvasId, commandSingle, commandMultiple);
        commandParser.run();
    }

    /**
     * The syntax button form GLP application is the entry point for validating all the command by the user input.
     * */
    @FXML
    protected void onSyntaxButtonClick() {

        String commandSingle = inputSingleCodeText.getText();
        String commandMultiple = inputMultipleCodeText.getText();

        CommandParser commandParser= new CommandParser(canvasId, commandSingle, commandMultiple);
        commandParser.syntax();
    }


}